# code is from: https://nni.readthedocs.io/en/stable/tutorials/hpo_nnictl/nnictl.html



search_space:
  features:
    _type: choice
    _value: [ 128, 256, 512, 1024 ]
  lr:
    _type: loguniform
    _value: [ 0.0001, 0.1 ]
  momentum:
    _type: uniform
    _value: [ 0, 1 ]

trial_command: python model.py
trial_code_directory: .    ## put `config.yaml` and `model.py` in the same directory

## Here we evaluate 10 sets of hyperparameters in total, and concurrently evaluate 2 sets at a time.
trial_concurrency: 2
max_trial_number: 10  ## or `max_experiment_duration = '1h'`
                      ## TPE needs 20 trials to warm up
tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
